In [10]:
import snscrape.modules.twitter as snt
import pandas as pd

# Getting Tweets from Ratan TATA

Model_1 = "Twitter"
tweets = []
limit = 500

for tweet in snt.TwitterSearchScraper(Model_1).get_items():
    #print(vars(tweet))
    #break
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.date,tweet.id,tweet.url,tweet.user.username,tweet.media,tweet.replyCount,tweet.retweetCount])
            
            
df = pd.DataFrame(tweets, columns = ["DateTime", "ID", "Text","User_Name","Media","ReplyCount","Retweet Count"])
display(df)

,DateTime,ID,Text,User_Name,Media,ReplyCount,Retweet Count
0,2023-01-21 11:12:28+00:00,1616755603413807108,https://twitter.com/mamimume_new/status/161675...,mamimume_new,None,0,0
1,2023-01-21 11:12:28+00:00,1616755602407165953,https://twitter.com/raiko82somen/status/161675...,raiko82somen,None,0,0
2,2023-01-21 11:12:27+00:00,1616755600842522625,https://twitter.com/fm_emm/status/161675560084...,fm_emm,None,0,0
3,2023-01-21 11:12:27+00:00,1616755600687353862,https://twitter.com/AEON_JAPAN/status/16167556...,AEON_JAPAN,None,0,0
4,2023-01-21 11:12:27+00:00,1616755598938484736,https://twitter.com/WpFMuvvdR8VdIoF/status/161...,WpFMuvvdR8VdIoF,None,0,0
...,...,...,...,...,...,...,...
495,2023-01-21 11:11:21+00:00,1616755320847581185,https://twitter.com/MAMelby/status/16167553208...,MAMelby,None,1,0
496,2023-01-21 11:11:20+00:00,1616755319475929088,https://twitter.com/debestridge/status/1616755...,debestridge,None,0,0
497,2023-01-21 11:11:20+00:00,1616755316925792259,https://twitter.com/nany7538/status/1616755316...,nany7538,None,0,0
498,2023-01-21 11:11:20+00:00,1616755316896714756,https://twitter.com/sinan_kanarya/status/16167...,sinan_kanarya,None,0,0
499,2023-01-21 11:11:20+00:00,1616755316657373186,https://twitter.com/ignite_GSD/status/16167553...,ignite_GSD,[Photo(previewUrl='https://pbs.twimg.com/media...,0,0